# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Name of the workflow
name: Selenium Automation - CI

# On attribute - This attribute is mandatory and specifies the trigger for this workflow.There are several actions you can include
# push, pull request, release etc.
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


# Under jobs attribute group together all the jobs that run in this workflow.
jobs:
  build:

# Configures the job to run on the latest version of an Ubuntu Linux runner. This means that the job will execute on a fresh virtual machine hosted by GitHub
    runs-on: ubuntu-latest
#
    steps:
# This is an action that checks out your repository onto the runner, allowing you to run scripts or other actions against your code (such as build and test tools).
    - uses: actions/checkout@v3
# This step uses the actions/setup-java@v3 action to install the specified version of the Java (this example uses v11).
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
    
    - name: Build with Maven
      run: mvn test -DsuiteXmlFile=testng.xml

    - name: Test Report
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
           name: SureFire Report
           path: target/surefire-report/
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
